stages:
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/

test:
  image: cypress/browsers:node12.14.1-chrome85-ff81
  stage: test
  script:
    - npm ci
    - npm run start:ci &
    - npx cypress run --browser chrome
    artifacts:
    when: always
    paths:
      - cypress/screenshots/**/*.png
    expire_in: 1 day